apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - beta.rallypoint.tech
        - rallypoint.tech
      secretName: front-tls
  rules:
    - host: beta.rallypoint.tech
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "fullname" . }}-clusteip
              servicePort: 80
    - host: rallypoint.tech
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "fullname" . }}-clusteip
              servicePort: 80
