# Default values for checkfront.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: rallypointtech/front
  tag: latest

imagePullSecrets: []

ENV_CONFIG: "prod"

env:
  NODE_ENV: "prod"


apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-downloads
  namespace: media
  labels:
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/transmission/downloads"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-config
  namespace: media
  labels:
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/transmission/config"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-downloads
  namespace: media
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
  namespace: media
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
